### ISSUE TITLE
ArchLinux AUR: cannot build and wrong deps

### ISSUE THREAD

**Issue by cinnamonmatexfce** [shumatech/gorom#2]
`make` fails because of:
```
# github.com/sciter-sdk/go-sciter
/home/username/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.1-0.20200602150116-89a4dd09b0f8/sciter.go:1052:142: cannot use _cgo1 (type *_Ctype_HWINDOW) as type **_Ctype_struct__GtkWidget in argument to _Cfunc_SciterGetElementHwnd
```

Also, wrong package name declared in PKGBUILD deps:
please fix `depends=('libsciter-gtk')` into `depends=('libsciter-gtk-bin')`

**Comment by shumatech** [comment]
The sciter go bindings are currently broken with go 1.15:
https://github.com/sciter-sdk/go-sciter/issues/245

libsciter-gtk-bin provides libsciter-gtk and should satisfy the package dependency

**Comment by cinnamonmatexfce** [comment]
`LC_ALL=C LANG=C pikaur gorom` try to install. but then fails here: `error: target not found: libsciter-gtk-bin`

But if I don't set LANG, then pikaur immediately complains it cannot find `libsciter-gtk` in the AUR (missing dependency).

**Comment by Raineer** [comment]
I was able to get this to build and run on Arch by manually downgrading Go to v1.14.11 and building gorom from git. I don't know enough about PKGBUILD (or Go) to know how to structure PKGBUILD to work with this configuration from AUR.

**Comment by shumatech** [comment]
Release 0.1.2 should build with all current versions of Go.
