### ISSUE TITLE
Check hashes of extra files

### ISSUE THREAD

**Issue by zerotohero** [shumatech/gorom#3]
Awesome utility! Unfortunately, I have a few messy ROM sets and would like to start tidying them up. Most of the file names appear to be off, and chkrom lists all of the ROMs in my set as "Extra." Any chance you could easily add the ability to match and rename these files instead? Maybe based on the checksum or something? Maybe I'm over simplifying the issue, but it would make the tool much more useful for me!

**Comment by shumatech** [comment]
The gorom chkrom and fixrom operations work by matching ROM files by checksum and will rename ROM files according to the name in the DAT file that matches the checksum.  If gorom reports a ROM as extra, then it couldn't find the checksum in the DAT file.

If you could provide more detail such as the layout of the ROM files, the DAT file contents, and what you are trying to accomplish, I can give you some pointers.  It could be a bad or mismatched DAT file or a file format gorom doesn't handle.

**Comment by zerotohero** [comment]
So the .dat file I'm using is the Dreamcast .dat file from redump. Clrmamepro seems to give me the output I'm expecting, but gorom just labels everything as extra. It's just a folder full of .7z files. Not sure what other info is necessary but maybe between a funny .dat file and .7z files something is going wrong?

**Comment by shumatech** [comment]
GoROM doesn't support 7z files, it expects ROM sets to be in ZIP files or extracted into directories.  You can uncompress your 7z files into directories and fix them up from there.  Most ROM sets these days use ZIPs since they can be more easily distributed in torrents.

**Comment by zerotohero** [comment]
It's only my larger sets that switched to 7z, I assume for better compression. But that would explain why gorom completely fails with them. Oh well, maybe something to put on the roadmap for later!

**Comment by shumatech** [comment]
Added support for reading rar, 7z, and tar.gz ROM archives and writing 7z and tar.gz (no rar).
