### ISSUE TITLE
Add support for header files.

### ISSUE THREAD

**Issue by Sinistral2099** [shumatech/gorom#7]
Add support for skipping headers on headered ROMs.

[header_nes.zip](https://github.com/shumatech/gorom/files/6834916/header_nes.zip)

**Comment by shumatech** [comment]
Can you provide a more detailed example of the issue?

**Comment by Sinistral2099** [comment]
So currently gorom doesn't recognize headered NES ROMs as matching the No-Intro dat files because it doesn't support the header file like clrmampro does. And most emulators need the headered ROMs because the header tells them what mappers it needs for that particular game. I attached the header file used by clrmamepro in my original comment.

With that file, clrmamepro checks the checksum in the dat + the headerfile and then properly recognizes headered ROMs.

**Comment by shumatech** [comment]
Added option to skip NES, A7800, and Lynx headers.
