### ISSUE TITLE
All 7z files are considered "Extra" in addition to being valid ROM files.

### ISSUE THREAD

**Issue by Sinistral2099** [shumatech/gorom#8]
When using --fixrom and --extra-trash gorom deletes all 7z files after verifying them. It is checking them, fixing them, but it also considered them extra and lists them after the fix/check results.

[scan results.txt](https://github.com/shumatech/gorom/files/7229191/scan.results.txt)

**Comment by shumatech** [comment]
This was caused by an inadvertent lower case conversion of the machine name.  It should be fixed in the latest commit.
